// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDlZE7aHdJN0_V5GSXV4CPCKOcNfmUF2M',
    appId: '1:564380464966:web:eb023f21cf47983cec9747',
    messagingSenderId: '564380464966',
    projectId: 'toku-55f46',
    authDomain: 'toku-55f46.firebaseapp.com',
    storageBucket: 'toku-55f46.appspot.com',
    measurementId: 'G-DZBJ3Y8E64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeVYkGF_rDM7lnW5Q1UT3m6Iyw5HR1yqo',
    appId: '1:564380464966:android:0186292188be985bec9747',
    messagingSenderId: '564380464966',
    projectId: 'toku-55f46',
    storageBucket: 'toku-55f46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6mPhBEWsh5_U1Dw8rIWOf_X9ypixhmnE',
    appId: '1:564380464966:ios:fa5dd2b622625b46ec9747',
    messagingSenderId: '564380464966',
    projectId: 'toku-55f46',
    storageBucket: 'toku-55f46.appspot.com',
    iosBundleId: 'com.example.toku',
  );
}
